### ISSUE TITLE
Is this library supposed to be used?

### ISSUE THREAD

**Issue by markg85** [ipfs-shipyard/js-hamt-sharding#2]
Hi,

I'm wondering if this is a play project that's not supposed to be used?
Or if it is definitely supposed to be used?

If it's the later, then it currently doesn't work at all anymore.
The following snippet does work:
```js
const hamt = require('hamt-sharding')
const crypto = require('crypto-promise')

// decide how to hash things, can return a Promise
const hashFn = async (value) => {
  return crypto.hash('sha256')(value).toString('hex');
}

const bucket = hamt({
  hashFn: hashFn
});

(async () => {
    try {
        await bucket.put('key', 'value')

        const output = await bucket.get('key')
        console.log(output)
    } catch (e) {
        console.error(e)
        // Deal with the fact the chain failed
    }
})();
```

I would recommend to change the install line to:
`npm install hamt-sharding crypto-promise`

As `crypto-promise` is required for this to work too. And unlikely to be there by default.

The snippet on the main page:
```js
// decide how to hash things, can return a Promise
const hashFn = async (value) => {
  return crypto
    .createHash('sha256')
    .update(value)
    .digest()
}
```

Doesn't work at all. The functions `createHash`, `update` and `digest` either don't exist or are not exposed. Or, entirely possible too, the author had more stuff included that exposed these things.

Anyhow, this does work:
```js
const hashFn = async (value) => {
  return crypto.hash('sha256')(value).toString('hex');
}
```

I'm asking this because i want to store a tree like structure in IPFS and am looking for a proper library to do that from node.js. This library seems quite promising! Would you advice me to use this library for that goal or would you recommend another one?

Cheers,
Mark

**Comment by lidel** [comment]
Hi @markg85, this library is internally used by js-ipfs for HAMT-sharding of huge directories on unixfs (dag-pb) so we maintain it,  however AFAIK it is not designed to be used outside that context (if is an implementation detail).

I suspect unifxs in general, may not be what you want to use for "arbitrary tree like structures". 
More flexible IPLD-CBOR data structures sound like a better match for your needs:

- support is built-in, just use `ipfs.dag.*` commands with `format: 'dag-cbor'` – see docs: https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DAG.md
- docs: https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-cbor.md
- js lib:  https://github.com/ipld/js-ipld-dag-cbor 

In case it does not work for your use case, please open support/question topic at https://discuss.ipfs.io/c/help/help-js-ipfs/25
(We use github only for bugs/feature requests)
